package br.com.concrete.tentacle.utils

const val EMPTY_STRING = ""
const val PREFS_KEY_USER_SESSION = "USER_SESSION"
const val DEFAULT_INVALID_RESOURCE = -1
const val BLANk_SPACE_STRING = " "

const val PLATFORM_PS3_ABBREV = "PS3"
const val PLATFORM_PS4_ABBREV = "PS4"
const val PLATFORM_XBOX_ONE_ABBREV = "XONE"
const val PLATFORM_XBOX_360_ABBREV = "X360"
const val PLATFORM_NINTENDO_SWITCH_ABBREV = "SWITCH"
const val PLATFORM_NINTENDO_3DS_ABBREV = "3DS"
const val PLATFORM_XBOX_ONE = "XBOXONE"
const val PLATFORM_XBOX_360 = "XBOX360"
const val PLATFORM_NINTENDO_SWITCH = "NINTENDOSWITCH"
const val PLATFORM_NINTENDO_3DS = "NINTENDO3DS"